cache:
  directories:
    - $HOME/node_modules

language: node_js

node_js:
  - "5"
  - "4"
  - "iojs"

matrix:
  include:
    - node_js: "0.12"
      script: "npm run lint && npm run unit-test && npm run feature-test-ignore-es6"
    - node_js: "0.10"
      script: "npm run lint && npm run unit-test && npm run feature-test-ignore-es6"

sudo: false
